server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: prefixpath_route
          uri: http://localhost:9000/
          predicates:
            - Host={teste}

        - id: client
          uri: http://localhost:8082/
          predicates:
            - Path=/mv-fatur-auditoria/**
